# Generated by Django 3.2.9 on 2021-11-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.ForeignKey(help_text='char(1 -> 20).', on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user_uid.')),
            ],
        ),
    ]
